// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkd8jQCJ12tvnRfgqya2dIx9WvpUIdWvs',
    appId: '1:468640782830:web:60386cf2472e3ea6da96ff',
    messagingSenderId: '468640782830',
    projectId: 'cyberlog-230ff',
    authDomain: 'cyberlog-230ff.firebaseapp.com',
    storageBucket: 'cyberlog-230ff.firebasestorage.app',
    measurementId: 'G-D4THRV406V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXImQu8LV7YOte449wAAqxddF0837fRA',
    appId: '1:468640782830:android:b055008e9bd70fedda96ff',
    messagingSenderId: '468640782830',
    projectId: 'cyberlog-230ff',
    storageBucket: 'cyberlog-230ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5j1Tymq7jZoWH3n6JDFO76CQUzCv8aY',
    appId: '1:468640782830:ios:1e72e7357de28b7dda96ff',
    messagingSenderId: '468640782830',
    projectId: 'cyberlog-230ff',
    storageBucket: 'cyberlog-230ff.firebasestorage.app',
    iosClientId: '468640782830-m4ce8rtko3imhdr2bmno0vh7lb6fvsmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.session13ClassroomAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp5j1Tymq7jZoWH3n6JDFO76CQUzCv8aY',
    appId: '1:468640782830:ios:1e72e7357de28b7dda96ff',
    messagingSenderId: '468640782830',
    projectId: 'cyberlog-230ff',
    storageBucket: 'cyberlog-230ff.firebasestorage.app',
    iosClientId: '468640782830-m4ce8rtko3imhdr2bmno0vh7lb6fvsmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.session13ClassroomAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkd8jQCJ12tvnRfgqya2dIx9WvpUIdWvs',
    appId: '1:468640782830:web:0db43add006d7876da96ff',
    messagingSenderId: '468640782830',
    projectId: 'cyberlog-230ff',
    authDomain: 'cyberlog-230ff.firebaseapp.com',
    storageBucket: 'cyberlog-230ff.firebasestorage.app',
    measurementId: 'G-PG7LCLVH4H',
  );
}
